CREATE TABLE table_schemas
(
    id BIGSERIAL PRIMARY KEY,
    column_types TEXT ARRAY NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)